version: '3.8'

services:
  # Base de données SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ctcneh-network

  # API CT_CNEH
  api:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CT_CNEH_DB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true
      - JwtSettings__SecretKey=votre_clé_secrète_très_longue_et_complexe_pour_la_sécurité_jwt_token_2024
      - JwtSettings__Issuer=CT_CNEH_API
      - JwtSettings__Audience=CT_CNEH_Client
    depends_on:
      - sqlserver
    networks:
      - ctcneh-network
    volumes:
      - ./wwwroot/uploads:/app/wwwroot/uploads

  # Interface web (optionnel)
  # web:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api
  #   networks:
  #     - ctcneh-network

volumes:
  sqlserver_data:

networks:
  ctcneh-network:
    driver: bridge
